<div class="container-fluid">
		<div class="row manage-table">

			<div class="progress" id="progress_container" style="display:none;margin-bottom:10px;">
				<div class="progress-bar progress-bar-striped active" role="progressbar" id="progessbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
				<span id="progress_percent">0</span>% <span id="progress_title">Complete</span> <span id="progress_message"></span>
				</div>
			</div>

			<div class="panel panel-piluku">
				<div class="panel-heading">
					<h3 class="panel-title">
					Items						<span title="3 total items" class="badge bg-primary tip-left" id="manage_total_items">3</span>
						<form id="config_columns">
						<div class="piluku-dropdown btn-group table_buttons pull-right m-left-20">
							<button type="button" class="btn btn-more dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<i class="ion-gear-a"></i>
							</button>
							
							<ul id="sortable" class="dropdown-menu dropdown-menu-left col-config-dropdown ui-sortable" role="menu" style="">
									<li class="dropdown-header"><a id="reset_to_default" class="pull-right"><span class="ion-refresh"></span> Reset</a>Column Configuration</li>
																		
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="item_id" value="item_id"><label class="sortable_column_name" for="item_id"><span></span>Item Id</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="item_number" value="item_number"><label class="sortable_column_name" for="item_number"><span></span>UPC/EAN/ISBN</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="name" value="name"><label class="sortable_column_name" for="name"><span></span>Name</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="category_id" value="category_id"><label class="sortable_column_name" for="category_id"><span></span>Category Full Path</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="cost_price" value="cost_price"><label class="sortable_column_name" for="cost_price"><span></span>Cost Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="unit_price" value="unit_price"><label class="sortable_column_name" for="unit_price"><span></span>Selling Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input checked="checked" name="selected_columns[]" type="checkbox" class="columns" id="quantity" value="quantity"><label class="sortable_column_name" for="quantity"><span></span>Quantity</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="product_id" value="product_id"><label class="sortable_column_name" for="product_id"><span></span>Product ID</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="barcode_name" value="barcode_name"><label class="sortable_column_name" for="barcode_name"><span></span>Barcode Display Name</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="category" value="category"><label class="sortable_column_name" for="category"><span></span>Category</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="supplier_company_name" value="supplier_company_name"><label class="sortable_column_name" for="supplier_company_name"><span></span>Supplier</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="location_cost_price" value="location_cost_price"><label class="sortable_column_name" for="location_cost_price"><span></span>Location Cost Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="location_unit_price" value="location_unit_price"><label class="sortable_column_name" for="location_unit_price"><span></span>Location Sellng price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="tax_group" value="tax_group"><label class="sortable_column_name" for="tax_group"><span></span>Tax Group</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="tags" value="tags"><label class="sortable_column_name" for="tags"><span></span>Tags</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="description" value="description"><label class="sortable_column_name" for="description"><span></span>Description</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="long_description" value="long_description"><label class="sortable_column_name" for="long_description"><span></span>Long Description</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="info_popup" value="info_popup"><label class="sortable_column_name" for="info_popup"><span></span>Information Popup when adding to sale</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="tax_included" value="tax_included"><label class="sortable_column_name" for="tax_included"><span></span>Prices include Tax</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="promo_price" value="promo_price"><label class="sortable_column_name" for="promo_price"><span></span>Promo Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="start_date" value="start_date"><label class="sortable_column_name" for="start_date"><span></span>Promo Start Date</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="end_date" value="end_date"><label class="sortable_column_name" for="end_date"><span></span>Promo End Date</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="reorder_level" value="reorder_level"><label class="sortable_column_name" for="reorder_level"><span></span>Reorder Level</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="expire_days" value="expire_days"><label class="sortable_column_name" for="expire_days"><span></span>Days to expiration</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="allow_alt_description" value="allow_alt_description"><label class="sortable_column_name" for="allow_alt_description"><span></span>Allow Alt Description</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_serialized" value="is_serialized"><label class="sortable_column_name" for="is_serialized"><span></span>Item has Serial Number</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="override_default_tax" value="override_default_tax"><label class="sortable_column_name" for="override_default_tax"><span></span>Override Default Tax</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_ecommerce" value="is_ecommerce"><label class="sortable_column_name" for="is_ecommerce"><span></span>Is Ecommerce Item</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="ecommerce_product_id" value="ecommerce_product_id"><label class="sortable_column_name" for="ecommerce_product_id"><span></span>E-Commerce Product ID</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="ecommerce_shipping_class_id" value="ecommerce_shipping_class_id"><label class="sortable_column_name" for="ecommerce_shipping_class_id"><span></span>E-Commerce Shipping Class</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_service" value="is_service"><label class="sortable_column_name" for="is_service"><span></span>Is Service</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_ebt_item" value="is_ebt_item"><label class="sortable_column_name" for="is_ebt_item"><span></span>Is EBT item</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="commission_amount" value="commission_amount"><label class="sortable_column_name" for="commission_amount"><span></span>Commission Amount</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="commission_percent" value="commission_percent"><label class="sortable_column_name" for="commission_percent"><span></span>Commission Percent</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="commission_percent_type" value="commission_percent_type"><label class="sortable_column_name" for="commission_percent_type"><span></span>Commission Percent Type</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="commission_fixed" value="commission_fixed"><label class="sortable_column_name" for="commission_fixed"><span></span>Commission Fixed Value</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="change_cost_price" value="change_cost_price"><label class="sortable_column_name" for="change_cost_price"><span></span>Change cost price during sale</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="disable_loyalty" value="disable_loyalty"><label class="sortable_column_name" for="disable_loyalty"><span></span>Disable Loyalty</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="replenish_level" value="replenish_level"><label class="sortable_column_name" for="replenish_level"><span></span>Replenish Level</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="max_discount_percent" value="max_discount_percent"><label class="sortable_column_name" for="max_discount_percent"><span></span>Max Discount</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="min_edit_price" value="min_edit_price"><label class="sortable_column_name" for="min_edit_price"><span></span>Minimum Manual Edit Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="max_edit_price" value="max_edit_price"><label class="sortable_column_name" for="max_edit_price"><span></span>Maximum Manual Edit Price</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="has_variations" value="has_variations"><label class="sortable_column_name" for="has_variations"><span></span>Has Variations</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="variation_count" value="variation_count"><label class="sortable_column_name" for="variation_count"><span></span># of Variations</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="last_modified" value="last_modified"><label class="sortable_column_name" for="last_modified"><span></span>Last Modified</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="last_edited" value="last_edited"><label class="sortable_column_name" for="last_edited"><span></span>Last Edited</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="weight" value="weight"><label class="sortable_column_name" for="weight"><span></span>Weight</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="weight_unit" value="weight_unit"><label class="sortable_column_name" for="weight_unit"><span></span>Weight Unit</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="dimensions" value="dimensions"><label class="sortable_column_name" for="dimensions"><span></span>Dimensions</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="allow_price_override_regardless_of_permissions" value="allow_price_override_regardless_of_permissions"><label class="sortable_column_name" for="allow_price_override_regardless_of_permissions"><span></span>Allow price override regardless of per…</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="only_integer" value="only_integer"><label class="sortable_column_name" for="only_integer"><span></span>Only allow items to be sold in whole n…</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_series_package" value="is_series_package"><label class="sortable_column_name" for="is_series_package"><span></span>Sold in a series</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="series_quantity" value="series_quantity"><label class="sortable_column_name" for="series_quantity"><span></span>Series Quantity</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="series_days_to_use_within" value="series_days_to_use_within"><label class="sortable_column_name" for="series_days_to_use_within"><span></span>Number of days series must be used wit…</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_barcoded" value="is_barcoded"><label class="sortable_column_name" for="is_barcoded"><span></span>Is Barcoded</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="item_inactive" value="item_inactive"><label class="sortable_column_name" for="item_inactive"><span></span>Inactive</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="default_quantity" value="default_quantity"><label class="sortable_column_name" for="default_quantity"><span></span>Default Quantity When Selling or Receiving</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="location" value="location"><label class="sortable_column_name" for="location"><span></span>Location at Store</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="disable_from_price_rules" value="disable_from_price_rules"><label class="sortable_column_name" for="disable_from_price_rules"><span></span>Disable From Price Rules</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="disable_related_sales_prompt" value="disable_related_sales_prompt"><label class="sortable_column_name" for="disable_related_sales_prompt"><span></span>Do not prompt on sales</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="disable_related_receivings_prompt" value="disable_related_receivings_prompt"><label class="sortable_column_name" for="disable_related_receivings_prompt"><span></span>Do not prompt on receivings</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="is_favorite" value="is_favorite"><label class="sortable_column_name" for="is_favorite"><span></span>Is Favorite</label><span class="handle ion-drag"></span></a></li>									
																			<li class="sort"><a><input name="selected_columns[]" type="checkbox" class="columns" id="loyalty_multiplier" value="loyalty_multiplier"><label class="sortable_column_name" for="loyalty_multiplier"><span></span>Loyalty Multiplier</label><span class="handle ion-drag"></span></a></li>									
																	</ul>
						</div>
						</form>
						<div class="panel-options custom">
								<div class="pagination pagination-top hidden-print  text-center" id="pagination_top">
											
								</div>
						</div>
					</h3>
					
					
					
				</div>
				<div class="panel-body nopadding table_holder table-responsive" id="table_holder">
					<table class="table tablesorter table-hover" id="sortable_table"><thead><tr><th data-sort-column="" class="leftmost"><input type="checkbox" id="select_all"><label for="select_all"><span></span></label></th><th data-sort-column="">Actions</th><th data-sort-column="item_id">Item Id</th><th data-sort-column="item_number">UPC/EAN/ISBN</th><th data-sort-column="name">Name</th><th data-sort-column="category">Category Full Path</th><th data-sort-column="cost_price">Cost Price</th><th data-sort-column="unit_price">Selling Price</th><th data-sort-column="quantity">Quantity</th><th data-sort-column="" class="rightmost">&nbsp;</th></tr></thead><tbody><tr style="cursor: pointer;"><td><input type="checkbox" id="item_3" value="3"><label for="item_3"><span></span></label></td><td class="actions"><div class="piluku-dropdown dropdown btn-group table_buttons upordown">
		  				 <a href="https://demo.phppointofsale.com/index.php/items/view/3?redirect=items" role="button" class="btn btn-more edit_action">Edit</a><button type="button" class="btn btn-more dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<i class="ion-more"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-left " role="menu"><li><a href="https://demo.phppointofsale.com/index.php/items/inventory/3?redirect=items" class="" title="Inventory"><i class="ion-android-clipboard"></i> Inventory</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/pricing/3?redirect=items" class="" title="Inventory"><i class="ion-cash"></i> Edit Pricing</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/qr_barcodes/3?redirect=items" class="" title="QR/Barcodes"><i class="ion-android-print"></i> Print QR/Barcodes</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/clone_item/3?redirect=items" class="clone_manage_table" title="Clone"><i class="ion-ios-browsers-outline"></i> Clone Item</a></li></ul>
						</div></td><td>3</td><td></td><td><a class="" href="https://demo.phppointofsale.com/index.php/home/view_item_modal/3?redirect=items" data-toggle="modal" data-target="#myModal">Chiken 1 box</a></td><td>Meat</td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/3?redirect=items&amp;quick_edit=1">$0.00</a></td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/3?redirect=items&amp;quick_edit=1">$450.00</a></td><td><a class="" href="https://demo.phppointofsale.com/index.php/items/inventory/3?redirect=items&amp;quick_edit=1">-0.0222222212</a></td><td><a href="https://demo.phppointofsale.com/assets/assets/images/default.png" class="rollover"><img src="https://demo.phppointofsale.com/assets/assets/images/default.png" alt="Chiken 1 box" class="img-polaroid" width="45"></a></td></tr><tr style="cursor: pointer;"><td><input type="checkbox" id="item_2" value="2"><label for="item_2"><span></span></label></td><td class="actions"><div class="piluku-dropdown dropdown btn-group table_buttons upordown">
		  				 <a href="https://demo.phppointofsale.com/index.php/items/view/2?redirect=items" role="button" class="btn btn-more edit_action">Edit</a><button type="button" class="btn btn-more dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<i class="ion-more"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-left " role="menu"><li><a href="https://demo.phppointofsale.com/index.php/items/inventory/2?redirect=items" class="" title="Inventory"><i class="ion-android-clipboard"></i> Inventory</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/pricing/2?redirect=items" class="" title="Inventory"><i class="ion-cash"></i> Edit Pricing</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/qr_barcodes/2?redirect=items" class="" title="QR/Barcodes"><i class="ion-android-print"></i> Print QR/Barcodes</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/clone_item/2?redirect=items" class="clone_manage_table" title="Clone"><i class="ion-ios-browsers-outline"></i> Clone Item</a></li></ul>
						</div></td><td>2</td><td>Repair Item</td><td><a class="" href="https://demo.phppointofsale.com/index.php/home/view_item_modal/2?redirect=items" data-toggle="modal" data-target="#myModal">Repair Item</a></td><td>Repair Item</td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/2?redirect=items&amp;quick_edit=1">$0.00</a></td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/2?redirect=items&amp;quick_edit=1">$0.00</a></td><td>N/A</td><td><a href="https://demo.phppointofsale.com/assets/assets/images/default.png" class="rollover"><img src="https://demo.phppointofsale.com/assets/assets/images/default.png" alt="Repair Item" class="img-polaroid" width="45"></a></td></tr><tr style="cursor: pointer;"><td><input type="checkbox" id="item_1" value="1"><label for="item_1"><span></span></label></td><td class="actions"><div class="piluku-dropdown dropdown btn-group table_buttons upordown">
		  				 <a href="https://demo.phppointofsale.com/index.php/items/view/1?redirect=items" role="button" class="btn btn-more edit_action">Edit</a><button type="button" class="btn btn-more dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<i class="ion-more"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-left " role="menu"><li><a href="https://demo.phppointofsale.com/index.php/items/inventory/1?redirect=items" class="" title="Inventory"><i class="ion-android-clipboard"></i> Inventory</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/pricing/1?redirect=items" class="" title="Inventory"><i class="ion-cash"></i> Edit Pricing</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/qr_barcodes/1?redirect=items" class="" title="QR/Barcodes"><i class="ion-android-print"></i> Print QR/Barcodes</a></li><li><a href="https://demo.phppointofsale.com/index.php/items/clone_item/1?redirect=items" class="clone_manage_table" title="Clone"><i class="ion-ios-browsers-outline"></i> Clone Item</a></li></ul>
						</div></td><td>1</td><td></td><td><a class="" href="https://demo.phppointofsale.com/index.php/home/view_item_modal/1?redirect=items" data-toggle="modal" data-target="#myModal">1111</a></td><td>111</td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/1?redirect=items&amp;quick_edit=1">$11.00</a></td><td><a href="https://demo.phppointofsale.com/index.php/items/pricing/1?redirect=items&amp;quick_edit=1">$111.00</a></td><td><a class="" href="https://demo.phppointofsale.com/index.php/items/inventory/1?redirect=items&amp;quick_edit=1">-9</a></td><td><a href="https://demo.phppointofsale.com/assets/assets/images/default.png" class="rollover"><img src="https://demo.phppointofsale.com/assets/assets/images/default.png" alt="1111" class="img-polaroid" width="45"></a></td></tr></tbody></table>			
				</div>		
				
			</div>
		</div>
	</div>